adapter_path: ./checkpoints/4b_Branch_Upgraded_NormalizedAdv_2000_No_Think_New_Prompt_T_1.0/policy/checkpoint-248
output_path: ./models/Branch-RL-4b_NormalizedAdv_2000_03_21
base_model: Qwen/Qwen3-4B-Instruct-2507